### PR TITLE
8/2

### PR DESCRIPTION
**Pull request by Maud-Pixel**
Here my solution for exercise 8.02

### CODE REVIEW

**Comment by NickBanken** [comment]
DS file slipped in

**Comment by NickBanken** [comment]
But now we got an gitignore file, all I want is the exercise. 😊 Almost there!

**Comment by NickBanken** [comment]
Some file got renamed?

**Comment by Maud-Pixel** [comment]
Hello Nick,

No, I didn't rename anything.

**Comment by NickBanken** [comment]
filechange

I says you have renamed some files :-)

**Pull request closed without merging**
